version: '3.0'
services:
  backend:
    build: ./web-app-tracker-backend
    ports:
      - "8000:8000"
  frontend:
    build: ./web-app-tracker
    ports:
      - "3000:3000"
    depends_on:
      - backend